#!/bin/bash
# install-voice-satellite.sh — Install Wyoming voice satellite for Nabla Edge
# Supports: button mode (Pi PTT) and wake mode (desktop openWakeWord)
#
# Usage:
#   sudo /opt/nabla-edge/voice/install-voice-satellite.sh [--mode button|wake]
#
# Creates:
#   - Python venv with wyoming-satellite
#   - Systemd user service wyoming-satellite.service
#   - HTTP listen endpoint service (nabla-voice-listen.service)
#   - Config file /etc/nabla-edge/voice.conf (if not exists)
#   - GPIO PTT helper (button mode, optional secondary trigger)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="/opt/nabla-edge/voice/venv"
CONFIG_DIR="/etc/nabla-edge"
CONFIG_FILE="$CONFIG_DIR/voice.conf"
SERVICE_DIR="$HOME/.config/systemd/user"
SATELLITE_PORT=10700
LISTEN_HTTP_PORT=10701

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[voice]${NC} $*"; }
warn() { echo -e "${YELLOW}[voice]${NC} $*"; }
err()  { echo -e "${RED}[voice]${NC} $*" >&2; }

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Install Wyoming voice satellite for Nabla Edge.

OPTIONS:
  --mode MODE       Set mode: button (default) or wake
  --port PORT       Satellite port (default: 10700)
  --name NAME       Satellite name (default: hostname)
  --help            Show this help

MODES:
  button   GPIO push-to-talk (recommended for Raspberry Pi)
  wake     Local openWakeWord via Docker (desktop/powerful hosts)

EXAMPLES:
  # Pi with PTT button on GPIO17
  sudo $(basename "$0") --mode button

  # Desktop with local wake word
  sudo $(basename "$0") --mode wake
EOF
  exit 0
}

check_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "Must run as root: sudo $0 $*"
    exit 1
  fi
}

get_real_user() {
  # Get the actual user (not root) for user systemd
  if [ -n "${SUDO_USER:-}" ]; then
    echo "$SUDO_USER"
  else
    logname 2>/dev/null || whoami
  fi
}

detect_audio_devices() {
  local mic="" spk=""
  
  # Try to find default/usable devices
  if command -v arecord &>/dev/null; then
    # Look for USB audio first, then default
    mic=$(arecord -L 2>/dev/null | grep -E '^plughw:' | head -1 || true)
    [ -z "$mic" ] && mic="default"
  fi
  
  if command -v aplay &>/dev/null; then
    spk=$(aplay -L 2>/dev/null | grep -E '^plughw:' | head -1 || true)
    [ -z "$spk" ] && spk="default"
  fi
  
  echo "$mic|$spk"
}

install_system_deps() {
  log "Installing system dependencies..."
  
  if command -v apt-get &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq \
      python3-venv \
      python3-pip \
      alsa-utils \
      pulseaudio-utils \
      2>/dev/null || true
    
    # GPIO support for Pi (button mode)
    if [ "$MODE" = "button" ]; then
      apt-get install -y -qq \
        python3-gpiozero \
        python3-lgpio \
        2>/dev/null || true
    fi
  else
    warn "Not Debian-based; ensure python3-venv, alsa-utils are installed"
  fi
}

create_venv() {
  log "Creating Python virtual environment..."
  
  mkdir -p "$(dirname "$VENV_DIR")"
  python3 -m venv "$VENV_DIR"
  
  # Upgrade pip
  "$VENV_DIR/bin/pip" install --upgrade pip wheel setuptools -q
  
  # Install wyoming-satellite
  # NOTE: We do NOT install webrtc/silero extras by default (SIGILL on old CPUs)
  log "Installing wyoming-satellite..."
  "$VENV_DIR/bin/pip" install wyoming-satellite -q
  
  # For button mode, ensure gpiozero is available in venv
  if [ "$MODE" = "button" ]; then
    "$VENV_DIR/bin/pip" install gpiozero lgpio -q 2>/dev/null || true
  fi
  
  log "Virtual environment ready: $VENV_DIR"
}

create_config() {
  log "Creating configuration..."
  
  mkdir -p "$CONFIG_DIR"
  
  if [ -f "$CONFIG_FILE" ]; then
    log "Config exists: $CONFIG_FILE (not overwriting)"
    return
  fi
  
  local hostname_default
  hostname_default="$(hostname -s 2>/dev/null || echo 'edge')"
  
  # Detect audio
  local audio_info mic_dev spk_dev
  audio_info="$(detect_audio_devices)"
  mic_dev="${audio_info%%|*}"
  spk_dev="${audio_info##*|}"
  
  cat > "$CONFIG_FILE" <<EOF
# Nabla Edge Voice Satellite Configuration
# Generated by install-voice-satellite.sh

MODE=$MODE
SATELLITE_NAME=$SATELLITE_NAME
HA_URL=https://example.invalid
HA_TOKEN_FILE=$CONFIG_DIR/ha-token
GPIO_PIN=$GPIO_PIN
WAKE_WORD=hey_jarvis
PORT=$SATELLITE_PORT
LISTEN_HTTP_PORT=$LISTEN_HTTP_PORT
MIC_DEVICE=$mic_dev
SPK_DEVICE=$spk_dev
WAKE_URI=tcp://127.0.0.1:10400
EOF
  
  chmod 644 "$CONFIG_FILE"
  log "Config written: $CONFIG_FILE"
  
  # Create placeholder token file
  if [ ! -f "$CONFIG_DIR/ha-token" ]; then
    echo "CHANGE_ME" > "$CONFIG_DIR/ha-token"
    chmod 600 "$CONFIG_DIR/ha-token"
    warn "Token placeholder created: $CONFIG_DIR/ha-token"
    warn "Replace with a real HA long-lived access token"
  fi
}

install_helper_scripts() {
  log "Installing helper scripts..."
  
  # Always install the HTTP listen endpoint (primary trigger via HA dashboard)
  local listen_script="/opt/nabla-edge/voice/nabla-voice-listen"
  if [ -f "$SCRIPT_DIR/nabla-voice-listen" ]; then
    cp "$SCRIPT_DIR/nabla-voice-listen" "$listen_script"
    chmod +x "$listen_script"
  fi
  ln -sf "$listen_script" /usr/local/bin/nabla-voice-listen 2>/dev/null || true
  log "HTTP listen endpoint installed: $listen_script"
  
  # GPIO PTT is optional secondary trigger (button mode only)
  if [ "$MODE" = "button" ]; then
    local ptt_script="/opt/nabla-edge/voice/nabla-voice-ptt"
    if [ -f "$SCRIPT_DIR/nabla-voice-ptt" ]; then
      cp "$SCRIPT_DIR/nabla-voice-ptt" "$ptt_script"
      chmod +x "$ptt_script"
    fi
    ln -sf "$ptt_script" /usr/local/bin/nabla-voice-ptt 2>/dev/null || true
    log "GPIO PTT script installed: $ptt_script (optional secondary trigger)"
  fi
}

create_systemd_service() {
  log "Creating systemd user service..."
  
  local real_user real_home
  real_user="$(get_real_user)"
  real_home="$(getent passwd "$real_user" | cut -d: -f6)"
  
  local svc_dir="$real_home/.config/systemd/user"
  mkdir -p "$svc_dir"
  
  # Build command line based on mode
  local extra_args=""
  if [ "$MODE" = "wake" ]; then
    extra_args='--wake-uri ${WAKE_URI} --wake-word-name ${WAKE_WORD}'
  fi
  
  cat > "$svc_dir/wyoming-satellite.service" <<EOF
[Unit]
Description=Wyoming Voice Satellite (Nabla Edge)
After=network.target sound.target
Wants=network.target

[Service]
Type=simple
EnvironmentFile=$CONFIG_FILE
ExecStart=$VENV_DIR/bin/python -m wyoming_satellite \\
    --uri tcp://0.0.0.0:\${PORT:-10700} \\
    --name \${SATELLITE_NAME:-edge} \\
    --mic-command "arecord -r 16000 -c 1 -f S16_LE -t raw -D \${MIC_DEVICE:-default}" \\
    --snd-command "aplay -r 22050 -c 1 -f S16_LE -t raw -D \${SPK_DEVICE:-default}" $extra_args
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
  
  chown "$real_user:$real_user" "$svc_dir/wyoming-satellite.service"
  
  # HTTP listen endpoint (primary trigger via HA dashboard / phone)
  cat > "$svc_dir/nabla-voice-listen.service" <<EOF
[Unit]
Description=Nabla Voice Listen HTTP Endpoint
After=wyoming-satellite.service
Wants=wyoming-satellite.service

[Service]
Type=simple
EnvironmentFile=$CONFIG_FILE
ExecStart=/opt/nabla-edge/voice/nabla-voice-listen
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
  chown "$real_user:$real_user" "$svc_dir/nabla-voice-listen.service"
  
  # GPIO PTT watcher (optional secondary trigger, button mode only)
  if [ "$MODE" = "button" ]; then
    cat > "$svc_dir/nabla-voice-ptt.service" <<EOF
[Unit]
Description=Nabla Voice PTT Button Watcher (optional)
After=wyoming-satellite.service
Wants=wyoming-satellite.service

[Service]
Type=simple
EnvironmentFile=$CONFIG_FILE
ExecStart=/opt/nabla-edge/voice/nabla-voice-ptt
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
    chown "$real_user:$real_user" "$svc_dir/nabla-voice-ptt.service"
  fi
  
  # Reload systemd for user
  sudo -u "$real_user" XDG_RUNTIME_DIR="/run/user/$(id -u "$real_user")" \
    systemctl --user daemon-reload 2>/dev/null || true
  
  log "Systemd services created in $svc_dir"
}

enable_services() {
  local real_user
  real_user="$(get_real_user)"
  local uid
  uid="$(id -u "$real_user")"
  
  log "Enabling services for user $real_user..."
  
  # Enable lingering so user services start at boot
  loginctl enable-linger "$real_user" 2>/dev/null || true
  
  # Enable the satellite service
  sudo -u "$real_user" XDG_RUNTIME_DIR="/run/user/$uid" \
    systemctl --user enable wyoming-satellite.service 2>/dev/null || true
  
  # Enable HTTP listen endpoint (primary trigger)
  sudo -u "$real_user" XDG_RUNTIME_DIR="/run/user/$uid" \
    systemctl --user enable nabla-voice-listen.service 2>/dev/null || true
  
  # GPIO PTT is optional, don't enable by default (user can enable if they wire a button)
  if [ "$MODE" = "button" ]; then
    log "GPIO PTT service available but not auto-enabled (optional secondary trigger)"
    log "To enable: systemctl --user enable nabla-voice-ptt"
  fi
  
  log "Services enabled (will start on next login or reboot)"
}

print_next_steps() {
  echo ""
  log "Installation complete!"
  echo ""
  echo "=== Next steps ==="
  echo ""
  echo "1. Edit configuration:"
  echo "   sudo nano $CONFIG_FILE"
  echo ""
  echo "2. Start services:"
  echo "   systemctl --user start wyoming-satellite"
  echo "   systemctl --user start nabla-voice-listen"
  echo ""
  echo "3. In Home Assistant:"
  echo "   a) Add the satellite:"
  echo "      Settings → Devices & Services → Add Integration → Wyoming"
  echo "      Host: <this-device-ip-or-hostname>"
  echo "      Port: $SATELLITE_PORT"
  echo ""
  echo "   b) Add a 'Listen' button to your dashboard (PRIMARY TRIGGER):"
  echo "      See instructions below for rest_command or shell_command."
  echo ""
  echo "=== HA Dashboard Listen Button (recommended) ==="
  echo ""
  echo "Add to configuration.yaml:"
  echo ""
  echo "  rest_command:"
  echo "    voice_satellite_listen:"
  echo "      url: http://<pi-ip>:$LISTEN_HTTP_PORT/listen"
  echo "      method: POST"
  echo ""
  echo "Then create a button card on your dashboard:"
  echo ""
  echo "  type: button"
  echo "  name: Listen"
  echo "  icon: mdi:microphone"
  echo "  tap_action:"
  echo "    action: call-service"
  echo "    service: rest_command.voice_satellite_listen"
  echo ""
  if [ "$MODE" = "button" ]; then
    echo "=== Optional: GPIO button (secondary trigger) ==="
    echo ""
    echo "If you also want a physical button on the Pi:"
    echo "  - Wire button between GPIO$GPIO_PIN and GND"
    echo "  - Enable: systemctl --user enable --now nabla-voice-ptt"
    echo ""
  fi
  if [ "$MODE" = "wake" ]; then
    echo "=== Wake word (desktop mode) ==="
    echo ""
    echo "Start local wake word (Docker):"
    echo "  docker run -d --name openwakeword \\"
    echo "    -p 127.0.0.1:10400:10400 \\"
    echo "    rhasspy/wyoming-openwakeword \\"
    echo "    --preload-model hey_jarvis"
    echo ""
  fi
}

# --- Main ---

MODE="button"
SATELLITE_NAME="$(hostname -s 2>/dev/null || echo 'edge')"
GPIO_PIN=17

while [ $# -gt 0 ]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    --port)
      SATELLITE_PORT="$2"
      shift 2
      ;;
    --name)
      SATELLITE_NAME="$2"
      shift 2
      ;;
    --help|-h)
      usage
      ;;
    *)
      err "Unknown option: $1"
      usage
      ;;
  esac
done

# Validate mode
case "$MODE" in
  button|wake) ;;
  *)
    err "Invalid mode: $MODE (use button or wake)"
    exit 1
    ;;
esac

check_root

log "Installing Wyoming satellite (mode=$MODE)..."

install_system_deps
create_venv
create_config
install_helper_scripts
create_systemd_service
enable_services
print_next_steps
