#!/bin/bash
# install-lva.sh — Install Linux Voice Assistant for Nabla Edge
#
# Usage:
#   sudo /opt/nabla-edge/voice/install-lva.sh [--name NAME] [--wake WORD]
#
# Installs LVA via Docker Compose from OHF-Voice/linux-voice-assistant.
# LVA uses ESPHome protocol (port 6053) and supports:
#   - assist_satellite.start_conversation
#   - assist_satellite.announce
#   - Wake word detection (microWakeWord)
#
# Prerequisites:
#   - Docker and Docker Compose
#   - PipeWire or PulseAudio for audio
set -euo pipefail

CONFIG_DIR="/etc/nabla-edge"
CONFIG_FILE="$CONFIG_DIR/voice.conf"
LVA_DIR="/opt/nabla-edge/voice/lva"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[lva]${NC} $*"; }
warn() { echo -e "${YELLOW}[lva]${NC} $*"; }
err()  { echo -e "${RED}[lva]${NC} $*" >&2; }

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Install Linux Voice Assistant (LVA) for Nabla Edge.

OPTIONS:
  --name NAME       Satellite name (default: hostname)
  --wake WORD       Wake word: hey_jarvis, ok_nabu, alexa, hey_mycroft
  --port PORT       ESPHome port (default: 6053)
  --help            Show this help

EXAMPLES:
  sudo $(basename "$0")
  sudo $(basename "$0") --name kitchen --wake hey_jarvis
EOF
  exit 0
}

check_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "Must run as root: sudo $0 $*"
    exit 1
  fi
}

check_docker() {
  if ! command -v docker &>/dev/null; then
    err "Docker is required but not installed."
    echo ""
    echo "Install Docker:"
    echo "  curl -fsSL https://get.docker.com | sh"
    echo "  sudo usermod -aG docker \$USER"
    echo ""
    exit 1
  fi
  
  if ! docker compose version &>/dev/null 2>&1; then
    err "Docker Compose v2 is required."
    echo "Ensure Docker is up to date."
    exit 1
  fi
}

load_config() {
  SATELLITE_NAME="$(hostname -s 2>/dev/null || echo 'edge')"
  WAKE_WORD="hey_jarvis"
  PORT=6053
  MODE="button"
  
  if [ -f "$CONFIG_FILE" ]; then
    # shellcheck disable=SC1090
    . "$CONFIG_FILE"
    SATELLITE_NAME="${SATELLITE_NAME:-$SATELLITE_NAME}"
    WAKE_WORD="${WAKE_WORD:-hey_jarvis}"
    PORT="${PORT:-6053}"
    MODE="${MODE:-button}"
  fi
}

save_config() {
  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Nabla Edge Voice Satellite Configuration (Linux Voice Assistant)
# Managed by install-lva.sh

MODE=$MODE
SATELLITE_NAME=$SATELLITE_NAME
WAKE_WORD=$WAKE_WORD
PORT=$PORT
GPIO_PIN=17
EOF
  chmod 644 "$CONFIG_FILE"
  log "Config saved: $CONFIG_FILE"
}

download_lva() {
  log "Downloading Linux Voice Assistant..."
  
  mkdir -p "$LVA_DIR"
  cd "$LVA_DIR"
  
  # Get latest version
  local lva_version
  lva_version=$(curl -s https://api.github.com/repos/OHF-Voice/linux-voice-assistant/releases/latest 2>/dev/null | grep -oP '"tag_name": "\K[^"]+' || echo "")
  
  if [ -n "$lva_version" ]; then
    log "Latest version: $lva_version"
    curl -fsSL "https://raw.githubusercontent.com/OHF-Voice/linux-voice-assistant/refs/tags/$lva_version/docker-compose.yml" -o docker-compose.yml
    curl -fsSL "https://raw.githubusercontent.com/OHF-Voice/linux-voice-assistant/refs/tags/$lva_version/.env.example" -o .env.example
  else
    warn "Could not determine latest version, using main branch"
    curl -fsSL "https://raw.githubusercontent.com/OHF-Voice/linux-voice-assistant/main/docker-compose.yml" -o docker-compose.yml
    curl -fsSL "https://raw.githubusercontent.com/OHF-Voice/linux-voice-assistant/main/.env.example" -o .env.example
  fi
}

create_env() {
  log "Creating configuration..."
  
  cd "$LVA_DIR"
  
  # Determine wake word setting based on mode
  local wake_enabled="true"
  if [ "$MODE" = "button" ]; then
    wake_enabled="false"
  fi
  
  cat > .env <<EOF
# Linux Voice Assistant configuration
# Generated by install-lva.sh

# Satellite name (appears in HA)
LVA_NAME=$SATELLITE_NAME

# ESPHome port
LVA_PORT=$PORT

# Wake word configuration
LVA_WAKE_WORD=$WAKE_WORD
LVA_WAKE_WORD_ENABLED=$wake_enabled

# Audio devices (auto-detected if empty)
# Use 'arecord -L' / 'aplay -L' to list available devices
# LVA_MIC_DEVICE=default
# LVA_SPEAKER_DEVICE=default
EOF
  
  log "Environment file created: $LVA_DIR/.env"
}

start_lva() {
  log "Pulling LVA Docker image..."
  cd "$LVA_DIR"
  docker compose pull
  
  log "Starting Linux Voice Assistant..."
  docker compose up -d
  
  # Wait a moment and check status
  sleep 3
  if docker compose ps | grep -q "running"; then
    log "LVA is running!"
  else
    warn "LVA may not have started correctly. Check: docker compose logs"
  fi
}

print_next_steps() {
  local ip_hint
  ip_hint="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [ -z "$ip_hint" ] && ip_hint="<this-device-ip>"
  
  echo ""
  log "Installation complete!"
  echo ""
  echo "=== Next steps ==="
  echo ""
  echo "1. In Home Assistant:"
  echo "   Settings → Devices & Services → Add Integration → ESPHome"
  echo "   Host: $ip_hint"
  echo "   Port: $PORT"
  echo ""
  echo "2. Entity created:"
  echo "   assist_satellite.${SATELLITE_NAME}_satellite_assist"
  echo "   supported_features: 3 (start_conversation + announce)"
  echo ""
  echo "3. Add dashboard button:"
  echo ""
  echo "   type: button"
  echo "   name: Listen"
  echo "   icon: mdi:microphone"
  echo "   tap_action:"
  echo "     action: call-service"
  echo "     service: assist_satellite.start_conversation"
  echo "     target:"
  echo "       entity_id: assist_satellite.${SATELLITE_NAME}_satellite_assist"
  echo ""
  echo "4. Manage LVA:"
  echo "   cd $LVA_DIR"
  echo "   docker compose logs -f    # View logs"
  echo "   docker compose restart    # Restart"
  echo "   docker compose down       # Stop"
  echo ""
}

# --- Main ---

load_config

while [ $# -gt 0 ]; do
  case "$1" in
    --name)
      SATELLITE_NAME="$2"
      shift 2
      ;;
    --wake)
      WAKE_WORD="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      ;;
    *)
      err "Unknown option: $1"
      usage
      ;;
  esac
done

check_root
check_docker
download_lva
create_env
save_config
start_lva
print_next_steps
